### ISSUE TITLE
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by rectof** [wwwg/kahoot.js#8]
> buffer.js:161
  throw new TypeError(kFromErrorMsg);
  ^

> TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:161:9)
    at new Buffer (buffer.js:131:17)
    at Function.decodeBase64 (C:\Users\Recto\Desktop\kahoot\node_modules\kahoot.js\src\token.js:59:10)
    at me.requestToken (C:\Users\Recto\Desktop\kahoot\node_modules\kahoot.js\src\token.js:74:22)
    at IncomingMessage.res.on.chunk (C:\Users\Recto\Desktop\kahoot\node_modules\kahoot.js\src\token.js:28:6)
    at emitOne (events.js:115:13)
    at IncomingMessage.emit (events.js:210:7)
    at IncomingMessage.Readable.read (_stream_readable.js:462:10)
    at flow (_stream_readable.js:833:34)
    at resume_ (_stream_readable.js:815:3)

Used to work before, no clue what's happened

**Comment by rectof** [comment]
nvm im autistic.


I have another issue though, when I try looping the join function, I get this error, I've tried just about everything and cant figure it out. Sorry if this is a hassle lol


> events.js:187
      throw err;
      ^
 

> Error: Unhandled "error" event. (USER_INPUT)
    at WSHandler.emit (events.js:185:19)
    at WSHandler.message (C:\Users\Recto\Desktop\discordBots\kahoot\node_modules\kahoot.js\src\WSHandler.js:241:8)
    at WebSocket.WSHandler.ws.on.msg (C:\Users\Recto\Desktop\discordBots\kahoot\node_modules\kahoot.js\src\WSHandler.js:26:7)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (C:\Users\Recto\Desktop\discordBots\kahoot\node_modules\ws\lib\WebSocket.js:143:47)
    at Receiver.dataMessage (C:\Users\Recto\Desktop\discordBots\kahoot\node_modules\ws\lib\Receiver.js:389:14)
    at Receiver.getData (C:\Users\Recto\Desktop\discordBots\kahoot\node_modules\ws\lib\Receiver.js:330:12)
    at Receiver.startLoop (C:\Users\Recto\Desktop\discordBots\kahoot\node_modules\ws\lib\Receiver.js:165:16)
    at Receiver.add (C:\Users\Recto\Desktop\discordBots\kahoot\node_modules\ws\lib\Receiver.js:139:10)

**Comment by TheTetrabyte** [comment]
I can help you with this issue right now, this is because the name is the same as another connected user. Use an auto incrementing number.

```js
count = 0;

setInterval(() => {
  count++;
  let name = `Bot-${count}`;
})
```

**Comment by TheTetrabyte** [comment]
How are you looping through this, also for anyone wondering what the first error was about.

That would be the kahoot room was no longer accessible. I'm gonna make a pull request or maybe even my own module to fix the issues I've found with this.

**Comment by Ekstropiya** [comment]
I am having the same problem with looping, I have tried multiple ways of making the names different every loop. It just dosen't work. I can't even join twice with totally different names like this:

`client.join(00000, "Lorem")`
`client.join(00000, "Ipsum")`

And it still dosen't work. I would really appreciate it if you helped me with this.
