### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by nitroxplunge** [wwwg/kahoot.js#9]
It seems that it's not able to join games anymore.

**Comment by lowj** [comment]
Really? I was thinking of useing this package to create an app, but if not...

**Comment by cooperkilian** [comment]
Was working on a project with this, figured out that the NPM package was way behind in version, replace the files in node_modules and changed a few lines of code, then it worked!

**Comment by nitroxplunge** [comment]
Awesome! Thanks!

**Comment by cooperkilian** [comment]
I first installed the package with ``npm install kahoot.js --save`` in the directory I was working in, I then downloaded the latest version of this repository and in node_modules I went into the kahoot.js directory and deleted all the files inside, replacing them with the files I downloaded from the repository. You will have leftover files from the repository, they aren't needed. Upon trying to run it you will get an error, I don't remember the exact error but once it happens go to the line of code where the error occurs and replace it with something that wont cause the error, I'm pretty sure I just commented it out.
Hope this helps.

**Comment by BlueTranquility** [comment]
I am also attempting to use this, but I don't understand the steps taken in the last comment, because I do not know where the error is taking place. Any help would be _greatly_ appreciated. The error I get is:

`module.js:544
    throw err;
    ^

Error: Cannot find module 'promise'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/Kahoot-bot/node_modules/kahoot.js/src/kahoot.js:2:15)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)`

But I cannot locate any file named module.js?
The answer is probably right there but I'm new to all of this ^_^
Thanks in advance, and sorry for bothering you!

**Comment by cooperkilian** [comment]
Sorry for the late reply, did you change all the files inside the node_modules directory?

**Comment by BlueTranquility** [comment]
I did, but I will try once more once I regain physical access. Thanks for the feedback! ^_^

**Comment by ghost** [comment]
can someone upload a fixed package to his/her account?

**Comment by uxmgod** [comment]
I'll do this once I have the time.

**Comment by ghost** [comment]
thank you

**Comment by JipFr** [comment]
Any chance you've gotten to it yet, @cooperkilian?

**Comment by csprl** [comment]
It seems to still work decently. The NPM package hasn't been updated, but you can install directly from GitHub with `npm install wwwg/kahoot.js` if you want to save yourself from the trouble of manually replacing the files. Hope this helps!

**Comment by lynxog** [comment]
the `question.answer(0)` doesn't work, does anyone have a solution for this?

**Comment by nitroxplunge** [comment]
@lynxmelynx I have the same problem

**Comment by lynxog** [comment]
@casperlofgren do you know what to do?
I really need this package ^_^

**Comment by csprl** [comment]
Last time I checked it answers correctly (check the scoreboard) but it doesn't show during the question. I don't know why this happens, and currently I don't have time to investigate.

**Comment by nitroxplunge** [comment]
@lynxmelynx Testing it I have found the same results as casper, it seems to have to do with a deprecated function on Kahoot's side. I don't know if there's a replacement though.

**Comment by theusaf** [comment]
Late reply, but if you are still using this old kahoot.js package, there are many things outdated with it. It works for the most part, but there are many things missing / broken, which are fixed in my version of this project, which can also be found on npm as "kahoot.js-updated." The reason why kahoot doesn't show the script answering was because the "submit" id was changed from 6 to 45.

Edit:
This package no longer works.
